spring:
  application:
    name: Notification-Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentheanh24102003@gmail.com
    password: luwj hszd rspx yhdm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:7092
    consumer:
      group-id: noti-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.horob1.*"
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="horob1" password="2410";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="horob1" password="2410";
server:
  port: 9150

eureka:
  instance:
    appname: NS_DEV1
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
